### PR TITLE
Expose Flic button press up/down events to Flutter listeners

### PR DESCRIPTION
**Pull request by komaxx**
Implements Feature Request #8

### CODE REVIEW

**Comment by butterbrain** [comment]
That's some great stuff Matthias!

I've pushed that to pub.dev as a new minor version 1.2.0 as more of a
change with the added function to the interface.

**Comment by komaxx** [comment]
Thank you for the merge Douglas :)

**Comment by butterbrain** [comment]
I can make you an admin to the repository if you want? You write better
Dart than I did when I wrote it... I keep seeing things I would do better
now, especially now there's null-safety and Dart 3 (O:

**Comment by komaxx** [comment]
Sure, I'm happy to help!

> I keep seeing things I would do better now, especially now there's null-safety and Dart 3 (O:

We never stop learning :D

**Comment by butterbrain** [comment]
There you go - I think giving you write access means you can push to the
main branch without having to wait for me (O:

**Pull request merged**
